/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kinectocean;

import edu.ufl.digitalworlds.j4k.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;

import javax.swing.JLabel;
import javax.swing.SwingConstants;
import edu.ufl.digitalworlds.j4k.J4KSDK;
import edu.ufl.digitalworlds.j4k.Skeleton;
import edu.ufl.digitalworlds.j4k.DepthMap;
import edu.ufl.digitalworlds.j4k.VideoFrame;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.PrintStream;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author LaurensGram
 */
public class MainFrame extends javax.swing.JFrame {

    boolean inGame = false;
    private MyKinect k;
    int panelWidth;
    int panelHeight;
    JLabel counter = new JLabel("");
    GamePanel p;
    JLabel menuLabel;
    JButton start;
    Dimension j;



    public boolean isInGame() {
        return inGame;
    }

    public MainFrame() {
        initComponents();
        // configureWindow();
        k = new MyKinect();


//        Dimension d = new Dimension(800,800);
//        this.setPreferredSize(d);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
        this.setResizable(true);
        p = new GamePanel();
        
        
        p.setParent(this);
        this.setContentPane(p);
        menuLabel = new JLabel("Main menu", SwingConstants.CENTER);
        menuLabel.setFont(menuLabel.getFont().deriveFont(64.0f));
        //p.add(textLabel, BorderLayout.CENTER);
        p.add(menuLabel);
        p.setVisible(true);
        this.pack();
        start = new JButton("Start Game");
        start.setPreferredSize(new Dimension(400, 100));
        start.setFont(start.getFont().deriveFont(48.0f));
        //start.size();
        p.setBackground(Color.ORANGE);
        p.add(start);
        p.oldxPoint = WIDTH / 4;
        System.out.println(p.oldxPoint - 10);

        p.count = 0;

        start.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //System.out.println(k.getJoint(MyKinect.head));

                p.setBackground(Color.cyan);
                menuLabel.setVisible(false);
                start.setVisible(false);
                inGame = true;
                p.seen.restart();
                k.start(J4KSDK.SKELETON);
                
            }
        });

        //p.add();
    }

    public void countUpdate() {

        counter.setText(Integer.toString(p.count));
        counter.setFont(menuLabel.getFont().deriveFont(64.0f));
        p.add(counter);

    }
    public void mainMenu(){
        
//        p.g.clearRect(0, 0, 800, 800);
        
//        start.setVisible(true);
//        menuLabel.setVisible(true);
//        
//        p.count = 0;
//        p.setBackground(Color.orange);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    MyKinect getKinect() {
        return k;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
